name: Build
on:
  push:
    paths:
      - 'src/*'
      - '.github/workflows/package-src.yml'

jobs:
  build:
    # Job name is Greeting
    name: Package source
    # This job runs on Linux
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m venv venv
        source ./venv/bin/activate
        pip install -r src/requirements.txt
